#!/bin/dash

# @throw Error: not a shrug repo
if [ ! -d .shrug ] 
then
	echo "$0: error: no .shrug directory containing shrug repository exists" 1>&2
	exit 1
fi

# @throw Error: wrong flag
while getopts ":am" opt
do
	case ${opt} in
		a)
			;;
		m)
			;;
		\?)
			echo "$0 [-a] -m commit-message" 1>&2
			exit 1
			;;
		:)
			echo "$0 [-a] -m commit-message" 1>&2 
			exit 1
			;;
	esac
done

# @throw Error: no flag
if [ $OPTIND -eq 1 ]
then
	echo "$0 [-a] -m commit-message" 1>&2
        exit 1
fi

changed=0
for filename in ".shrug/index"/*
do
	
	if [ -f ".shrug/local/${filename##*/}" ]
	then
		if cmp -s "$filename" ".shrug/local/${filename##*/}"
		then
			continue
		else
			changed=1
		fi
		rm ".shrug/local/${filename##*/}"
	else
		changed=1
	fi
	cp "$filename" ".shrug/local/${filename##*/}"
done
if [ $changed -eq 0 ]
then
	echo "nothing to commit"
	exit 1
fi

commitSeq=$(ls -l .shrug/commit/ | egrep '^d' | wc -l)

mkdir .shrug/commit/"$commitSeq"
commitMsg=$(echo "$@" | sed 's/^-[am]* //' | sed  's/^-[am]* //')
echo "$commitMsg" > ".shrug/commit/$commitSeq/msg"
echo "Committed as commit $commitSeq"

cp .shrug/index/* .shrug/commit/"$commitSeq"/
