#!/bin/dash

# Error if shrug-add gets called before shrug=init
[ ! -d .shrug ] && echo "$0: error: no .shrug directory containing shrug repository exists" 1>&2 && exit 1

for filename in $@
do
	if [ ! -f "$filename" ] && [ ! -f .shrug/index/"$filename" ] 
	then
		echo "$0: error: can not open '$filename'"
		exit 1
	fi
done

for filename in $@
do
	if [ ! -f "$filename" ] && [ -f .shrug/index/"$filename" ]
	then
		rm .shrug/index/"$filename"
		continue
	fi
	cp "$filename" .shrug/index/
done 
