#!/bin/dash

# @throw Error: not a shrug repo
if [ ! -d .shrug ] 
then
	echo "$0:  error: no .shrug directory containing shrug repository exists" 1>&2
	exit 1
fi

# @throw Error: wrong flag
while getopts ":am" opt
do
	case ${opt} in
		a)
			;;
		m)
			;;
		\?)
			echo "$0 [-a] -m commit-message" 1>&2
			exit 1
			;;
		:)
			echo "$0 [-a] -m commit-message" 1>&2 
			exit 1
			;;
	esac
done

# @throw Error: no flag
if [ $OPTIND -eq 1 ]
then
	echo "$0 [-a] -m commit-message" 1>&2
        exit 1
fi



