#!/bin/dash

# @throw Error: not a shrug repo
if [ ! -d .shrug ] 
then
	echo "$0: error: no .shrug directory containing shrug repository exists" 1>&2
	exit 1
fi

force=0
cache=0

if echo "$@" | grep -Eq '\s?--force\s?'
then
	force=1
fi

if echo "$@" | grep -Eq '\s?--cached\s?'
then
        cache=1
fi
filesToRemove=$(echo "$@" | sed 's/--force//' | sed 's/--cached//')

#if [ $filesToRemove = "" ]
#then
#	echo "usage: shrug-rm [--force] [--cached] <filenames>" 1>&2
#        exit 1
#fi

# whether file exit in index
for filename in $filesToRemove
do
	if [ ! -f .shrug/index/"$filename" ]
	then
		echo "$0: error: '$filename' is not in the shrug repository" 1>&2
		exit 1
	fi
done

if [ $force -eq 1 ]
then
	for filename in $filesToRemove
	do
		if [ $cache -eq 0 ]
		then
			rm -f "$filename"
		fi

		rm -f .shrug/index/"$filename"
	done
elif [ $cache -eq 1 ] && [ $force -eq 0 ]
then
	for filename in $filesToRemove
	do
		if [ -f "$filename" ] && \
		   ! diff -Nu "$filename" .shrug/index/"$filename" >/dev/null && \
                   ! diff -Nu .shrug/index/"$filename" .shrug/local/"$filename"  >/dev/null && \
                   ! diff -Nu "$filename" .shrug/local/"$filename"  >/dev/null
		then
			echo "$0: error: '$filename' in index is different to both working file and repository" 1>&2
                        exit 1
		fi
		rm .shrug/index/"$filename"
	done
else
	for filename in $filesToRemove
	do 
		if ! diff -Nu "$filename" .shrug/index/"$filename" >/dev/null && \
		   ! diff -Nu .shrug/index/"$filename" .shrug/local/"$filename"	 >/dev/null && \
		   ! diff -Nu "$filename" .shrug/local/"$filename"  >/dev/null
		then
			echo "$0: error: '$filename' in index is different to both working file and repository" 1>&2
			exit 1
		elif ! diff -Nu "$filename" .shrug/index/"$filename" >/dev/null && \
		      diff -Nu .shrug/index/"$filename" .shrug/local/"$filename"   >/dev/null
		then
			echo "$0: error: '$filename' in repository is different to working file" 1>&2
			exit 1

		elif [ -f "$filename" ] && [ -f .shrug/index/"$filename" ] && [ ! -f .shrug/local/"$filename" ]
		then
			echo "$0: error: '$filename' has changes staged in the index" 1>&2
                        exit 1
		elif ! diff -Nu .shrug/index/"$filename" .shrug/local/"$filename"   >/dev/null
		then
			echo "$0: error: '$filename' has changes staged in the index" 1>&2
			exit 1
		else
			rm "$filename"
			rm .shrug/index/"$filename"
		fi
	done
fi
