#!/bin/dash

# Error if shrug-add gets called before shrug=init
[ ! -d .shrug ] && echo "$0: error: no .shrug directory containing shrug repository exists" 1>&2 && exit 1

for filename in $@
do
	if [ ! -f ./"$filename" ] 
	then
		echo "$0: error: can not open '$filename'"
		exit 1
	fi
done

for filename in $@
do
	if [ -f .shrug/index/"$filename" ]
	then
		rm ./.shrug/index/"$filename"
	fi
	cp ./"$filename" ./.shrug/index/
done 
